/*
 * config.h - Kconfig-derived build configuration
 *
 * Any source file that needs to test a Kconfig symbol from C
 * (#if SOME_SYMBOL) should #include <config.h>, which pulls in the
 * generated obj/autoconf.h (found via -Iobj in the Makefile's INCLUDE) --
 * the same convention pTOS itself uses. Nothing in libcmini needs this
 * today: the architecture choice is tested via the compiler's own
 * __arm__ built-in rather than a Kconfig symbol, and STDIO_WITH_LONG_LONG/
 * STDIO_MAP_NEWLINE are passed directly as -D flags by the Makefile. But
 * obj/autoconf.h is generated by every `make <name>_defconfig`/menuconfig
 * regardless, so this is here and ready for whenever a future option does
 * need C-level visibility, rather than requiring that wiring to be
 * reinvented at that point.
 */

#ifndef CONFIG_H
#define CONFIG_H

#include "autoconf.h"

#endif /* CONFIG_H */
